### ISSUE TITLE
Width infinitely grows when adding table-bordered css class

### ISSUE THREAD

**Issue by frankcalise** [pupudu/window-table#22] opened 2019-06-11 10:19 UTC
If I add table-bordered to this className attribute, the table starts out with the desired width defined by the parent but then grows quickly overtime (if you inspect, the width keeps increasing). Have you run into this at all? Bootstrap 3.3.7, I'll see if I can make a contrived example on Codesandbox.
```
<Html5Table
  className="table-condensed table-hover table-striped"
  data={data}
  height={this.props.size.height - 150}
  rowHeight={35}
  columns={this.columns}
/>
```

**Comment by pupudu** [comment] 2019-06-11 13:36
Hi @frankcalise 
Thank you for creating the issue. 

I created a sandbox, and I don't see any issues: https://codesandbox.io/s/window-table-basic-example-03juq

So my guess is either you are using an old version of window-table, or there's something else conflicting with the table. Can you try to reproduce the issue in this sandbox, please?

Also, maybe it's the browser or the operating system. Can you mention the browser you are using and your operating system as well? I can check on browser-stack to reproduce the issue then. 

Cheers.

**Comment by frankcalise** [comment] 2019-06-12 00:32
Yeah I'll try to reproduce. It's probably the way I'm trying to come up with 3 columns (to hold 3 tables) but have them all the height of the window. Also they live in an antd card (wasn't my choice but it's there) and with bootstrap. So there are plenty of styles going on something could be conflicting somewhere.

Thanks for the response.

**Comment by pupudu** [comment] 2019-06-13 22:24
Hi @frankcalise 
Have you had any luck to reproduce the issue? 
Are you still seeing the issue even after updating the table to the latest version? If so, can you mention the versions of each of the libraries you are using so that I can give it a go myself? 
Thanks

**Comment by pupudu** [comment] 2019-10-28 03:50
Closing assuming the issue is fixed. Please feel free to re-open if the issue persists.

**Closed by pupudu** 2019-10-28 03:50 UTC
