### ISSUE TITLE
Blank table when fast scrolling on MS Edge

### ISSUE THREAD

**Issue by thunderkid** [pupudu/window-table#32] opened 2019-10-15 17:26 UTC
If I open the demo site `https://window-table.now.sh/` on MS-Edge (Windows 10 1903 build) and scroll slowly, it works ok. But if I scroll quickly, the body of the table suddenly goes blank, and stays blank even if I then scroll slowly.

![image](https://user-images.githubusercontent.com/6183356/66854027-69de6b00-ef35-11e9-94d2-704f77480add.png)

**Comment by pupudu** [comment] 2019-10-15 23:23
Hi @thunderkid 
Thanks for reporting this issue. This issue can be reproduced on browser-stack. 

My initial guess is that this is either a performance issue in MS Edge or a limitation of react-window (the base library which enables table virtualization). I've seen similar behavior in Chrome when the row count is millions. 

It seems MS Edge can't handle more than 22000+ rows.
![Imgur](https://imgur.com/b2U0cjy)

Technically, I don't see why the number of rows becomes a problem since html elements are added and deleted as we scroll. I'll check with react-window as well, to see if there is a solution for this.

**Comment by thunderkid** [comment] 2019-10-16 00:21
Yes, now that you mention it I'm seeing that the error occurs after row 22k.
Which makes no sense - I'd have thought that since DOM elements are added dynamically, MS Edge shouldn't even know or care which row it's on. It should always think it's only displaying about 12 rows.

**Comment by pupudu** [comment] 2019-10-16 01:03
Yea I agree. I am gonna throw this question at Brian Vaughn. He will have a logical explanation for this. I need to reproduce the problem solely from react-window before that. I'll try to do that today or tomorrow eod.

**Comment by pupudu** [comment] 2020-02-06 21:49
This issue has been fixed in the latest Edge browser (thanks to the new chromium-based engine)

**Closed by pupudu** 2020-02-06 21:49 UTC
